# Generated by Django 5.1.2 on 2024-10-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=17)),
                ('key', models.CharField(max_length=255)),
                ('m3u', models.URLField()),
            ],
        ),
    ]
